### ISSUE TITLE
Error when load playground, Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by mulyoved** [sachinraja/trpc-playground#39]
Hi, 

1st time trying to use the library

loading http://localhost:3000/api/trpc-playground

get this error, 

error - TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at buildTrpcTsType (file:///C:/orderio04/node_modules/trpc-playground/dist/chunk-W4SFKB57.js:210:10)
    at Object.zodResolveTypes [as resolveTypes] (file:///C:/orderio04/node_modules/trpc-playground/dist/chunk-W4SFKB57.js:231:12)
    at file:///C:/orderio04/node_modules/trpc-playground/dist/chunk-YNRQKXGS.js:17:38
    at file:///C:/orderio04/node_modules/uttp/dist/chunk-4QB5FPND.js:9:30
    at eval (webpack-internal:///(api)/./pages/api/trpc-playground.ts:13:96) {
  page: '/api/trpc-playground'
}

Any hint where to check?

**Comment by sachinraja** [comment]
we need a reproduction

**Comment by mulyoved** [comment]
closing this, due to using old trpc version
